// Mocks generated by Mockito 5.0.16 from annotations
// in calculadora_imc/test/home.controller_test.dart.
// Do not manually edit this file.

import 'package:calculadora_imc/home/home.controller.dart' as _i4;
import 'package:calculadora_imc/imc.util.dart' as _i3;
import 'package:calculadora_imc/models/imcResultado.model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeImcResultado_0 extends _i1.Fake implements _i2.ImcResultado {}

class _FakeImcUtil_1 extends _i1.Fake implements _i3.ImcUtil {}

/// A class which mocks [ImcUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockImcUtil extends _i1.Mock implements _i3.ImcUtil {
  MockImcUtil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ImcResultado calcularImc(int? peso, int? altura) =>
      (super.noSuchMethod(Invocation.method(#calcularImc, [peso, altura]),
          returnValue: _FakeImcResultado_0()) as _i2.ImcResultado);
  @override
  String toString() => super.toString();
}

/// A class which mocks [HomeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeController extends _i1.Mock implements _i4.HomeController {
  MockHomeController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ImcUtil get imcUtil => (super.noSuchMethod(Invocation.getter(#imcUtil),
      returnValue: _FakeImcUtil_1()) as _i3.ImcUtil);
  @override
  _i2.ImcResultado calcular(int? peso, int? altura) =>
      (super.noSuchMethod(Invocation.method(#calcular, [peso, altura]),
          returnValue: _FakeImcResultado_0()) as _i2.ImcResultado);
  @override
  String toString() => super.toString();
}
